package WeatherPrediction.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CelsiusTemperature = 0;
  public static final int PredictionList = 1;
  public static final int PredictionResult = 2;
  public static final int Temperature = 3;
  public static final int Time = 4;
  public static final int WeatherData = 5;
  public static final int WeatherTimedData = 6;
  public static final int fahrenheit = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL);
    builder.put(0xa2c398ee236772aL, CelsiusTemperature);
    builder.put(0xa2c398ee2360af5L, PredictionList);
    builder.put(0x6fcf2f9c439dc0a9L, PredictionResult);
    builder.put(0xa2c398ee2361f51L, Temperature);
    builder.put(0xa2c398ee2361f48L, Time);
    builder.put(0x6fcf2f9c439dc0acL, WeatherData);
    builder.put(0xa2c398ee2361f42L, WeatherTimedData);
    builder.put(0xa2c398ee2372dffL, fahrenheit);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
