package WeatherPrediction.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myTemperature__BehaviorDescriptor = new Temperature__BehaviorDescriptor();
  private final BHDescriptor myCelsiusTemperature__BehaviorDescriptor = new CelsiusTemperature__BehaviorDescriptor();
  private final BHDescriptor myfahrenheit__BehaviorDescriptor = new fahrenheit__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt_a0g = concept;
    switch (index_846f5o_a0g.index(cncpt_a0g)) {
      case 0:
        return myCelsiusTemperature__BehaviorDescriptor;
      case 1:
        return myTemperature__BehaviorDescriptor;
      case 2:
        return myfahrenheit__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0g = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee236772aL), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2361f51L), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2372dffL)).seal();
}
