package WeatherClasses.structure;

/*Generated by MPS */


public class PredictionList {
  /*package*/ String name;

  public String getName() {
    return name;
  }
  public void setName(String name1) {
    name = name1;
    System.out.println("dlfkdlfdlkf");

  }
}
