package WeatherClasses.structure;

/*Generated by MPS */


public class Temperature {
  /*package*/ double value;
  /*package*/ String unit;
  public Temperature(double value, String unit) {
    this.value = value;
    this.unit = unit;
  }
}
