package WeatherClasses.structure;

/*Generated by MPS */


public class WeatherTimedData {
  /*package*/ int hours;
  /*package*/ int minutes;
  /*package*/ Temperature temperature;

  public WeatherTimedData(int hours1, int minutes1, Temperature temperature1) {
    hours = hours1;
    minutes = minutes1;
    temperature = temperature1;
  }
}
