package WeatherPrediction.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0a = ((SAbstractConcept) concept);
    switch (index_xbvbvu_a0a.index(cncpt_a0a)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new PredictionList_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new PredictionResult_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Temperature_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Time_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new WeatherData_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new WeatherTimedData_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt_a0d = concept;
    switch (index_xbvbvu_a0d.index(cncpt_a0d)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new PredictionResult_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex index_xbvbvu_a0a = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2360af5L), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0x6fcf2f9c439dc0a9L), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2361f51L), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2361f48L), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0x6fcf2f9c439dc0acL), MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0xa2c398ee2361f42L)).seal();
  private static final ConceptSwitchIndex index_xbvbvu_a0d = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3c2871aecbd349c9L, 0xbb563e9f18911c6bL, 0x6fcf2f9c439dc0a9L)).seal();
}
