package WeatherPrediction.sandbox;

/*Generated by MPS */

import WeatherClasses.structure.PredictionList;
import java.util.Deque;
import WeatherClasses.structure.WeatherTimedData;
import jetbrains.mps.internal.collections.runtime.LinkedListSequence;
import java.util.LinkedList;

public class PredictionListImpl extends PredictionList {
  /*package*/ String name = "Moscow";
  /*package*/ Deque<WeatherTimedData> input = LinkedListSequence.fromLinkedListNew(new LinkedList<WeatherTimedData>());
  /**
   * 
   */
  public PredictionListImpl() {
    LinkedListSequence.fromLinkedListNew(input).addElement(<!TextGen not found for 'WeatherPrediction.structure.WeatherData'!>);
    LinkedListSequence.fromLinkedListNew(input).addElement(<!TextGen not found for 'WeatherPrediction.structure.WeatherData'!>);
  }
}
